# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b94bfb4fcd39aa8f525647fd4da43581f0ee23254a54ac1b4b0f0c2bc14d4b6e27e7e609646c3c87a29009d44ddf758092e8e135f069ed8149575d6b8f4ef505

test:
  secret_key_base: 746892bc3a0c5ddf3d06cfefb8f77d5487bfcd42b7b672aeed86fecd9e804d79c5e06859763bea1644126cd2c8110ae6749711ace3cc450fe2f39523a41df550

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
